[book]
authors = ["racfop"]
language = "en"
multilingual = false
src = "src"
title = "Developers"


[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1     # the depth to start folding
